### ISSUE TITLE
Wrong "style" prop in "options" regarding to spec

### ISSUE THREAD

**Issue by ixrock** [eemeli/intl-pluralrules#1]
Regarding to specification:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules 
second argument `options` defines `type`, not `style` as in your implementation for "cardinal" or "ordinal" values.

e.g. should be `new Intl.PluralRules("en-US", {type: "ordinal"})`

Please fix this small issue and thank you for polyfill!

**Comment by eemeli** [comment]
The fix is now in the master branch, but it looks like my dev dependencies are full of `"*"` and the build system still uses make, so I'll need to port the whole thing to something more modern to make sense of it and fix the output. I'd happy to accept a PR for that; it might take me some number of days to get this fixed.

**Comment by eemeli** [comment]
s/number of days/number of hours/

v0.2.0 is now available on npm.

**Comment by ixrock** [comment]
Great! But now import is totally broken for me :)

```
0] ERROR in ./node_modules/intl-pluralrules/plural-rules.js
[0] Module not found: Error: Can't resolve 'make-plural/umd/pluralCategories' in './node_modules/intl-pluralrules'
[0]  @ ./node_modules/intl-pluralrules/plural-rules.js 15:24-67
[0]  @ ./node_modules/intl-pluralrules/polyfill.js
[0]  @ ./client/i18n/i18n.ts
[0]  @ ./client/i18n/index.ts
[0]  @ ./client/components/app.tsx
...
```

**Comment by eemeli** [comment]
@ixrock Oops, sorry, I'd left make-plural as a dev dependency. Try again with 0.2.1?

**Comment by ixrock** [comment]
@eemeli Now it works perfect! Many thanks :)
