### ISSUE TITLE
`getSelector` always returns undefined

### ISSUE THREAD

**Issue by forestwelch** [eemeli/intl-pluralrules#13]
https://github.com/eemeli/intl-pluralrules/blob/bdf0ba2412cf19c441ebe0c03f910be5c7e45d57/src/plural-rules.mjs#L12

The object `Plurals` returned from `make-plural/plurals` is shaped like so:

```
Plurals = {
   default: {
      af: func,
      ar: func,
      ...
   }
}
```

The right selector needs to be found like so (or something else needs to be done to account for this `default` object): 
```
const getSelector = lc => Plurals.default[id(lc)]
```

**Comment by eemeli** [comment]
Please verify that your `intl-pluralrules` is fetching version 6.0.1 of `make-plural`; there was a bug in its 6.0.0 release. If that is the case, could you give more details about the environment where you encountered this?

**Comment by jcestibariz** [comment]
I have the same problem, `make-plural` is v6.0.1, I'm running on IE11.

**Comment by eemeli** [comment]
@jcestibariz What's the bundler that you're using? And any chance of making a minimal test case available somewhere?

**Comment by jcestibariz** [comment]
I'm using Webpack v4.41.2.

**Comment by jcestibariz** [comment]
It works fine in a brand new project but fails in my old one.

**Comment by jcestibariz** [comment]
I found the problem: in my Webpack configuration I had `resolve: {extensions: ['.js', '.jsx']}` changing it to  `resolve: {extensions: ['.mjs', '.js', '.jsx']}` fixes this issue. (The order is important: `.mjs` must be before `.js`)

**Comment by eemeli** [comment]
Closing as fixed.
