### ISSUE TITLE
No support for most locales

### ISSUE THREAD

**Issue by forestwelch** [eemeli/intl-pluralrules#14]
The `make-plural` library you use only contains a reference to an `en` locale tag, as opposed to the following: `en-US`, `en-AU`, `en-CA`, `en-GB`, etc. None of these will work, and there is no logic to consider all of those locales to fall under `en` for the purposes of pluralization.

**Comment by eemeli** [comment]
The logic you're looking for [is here](https://github.com/eemeli/intl-pluralrules/blob/master/src/factory.mjs#L50), and all of the examples you've given will work fine.

**Comment by eemeli** [comment]
Closing as answered.
