### ISSUE TITLE
Polyfill not working on Angular 7

### ISSUE THREAD

**Issue by clintcfavor** [eemeli/intl-pluralrules#16]
Using v1.1.2

![image](https://user-images.githubusercontent.com/19337016/76305556-5080f580-6300-11ea-8efa-529327150e48.png)

**Comment by eemeli** [comment]
@clintcfavor @Eric24 I've just released version 1.2.0, which vendors in the make-plural dependency. Could you check whether that resolves this issue?

**Comment by eemeli** [comment]
Closing, as presumably fixed.
