### ISSUE TITLE
Which browserify/babel options should I be using?

### ISSUE THREAD

**Issue by elisehein** [eemeli/intl-pluralrules#17]
I'm trying to get this to work in a React app that is built using browserify and @babel/preset-env. Here's a minimal example of my setup:

#### `package.json` dependencies: 

```
"dependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "babel-core": "^7.0.0-bridge.0",
    "babelify": "^10.0.0",
    "browserify": "^16.2.3",
    "intl-pluralrules": "^1.2.0"
  }
```

#### `.babelrc`:

```
{
  "presets": ["@babel/preset-env"]
}
```

#### `index.js`:

```
import "intl-pluralrules";
```

Trying to build index.js using browserify, I get the following error:

```
> ./node_modules/.bin/browserify -t [ babelify ] index.js

./node_modules/intl-pluralrules/factory.mjs:180
export default getPluralRules;
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Is there a pre-build step that I need to run for `intl-pluralrules`, or should I be importing a different file..?

My workaround right now is to make use of [`global` and `ignore`](https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed) in browserify to apply the babelify transforms to `intl-pluralrules` before importing. I'd rather not do this.

---

**EDIT**: Ideally I'd like a way to create an `intl-pluralrules.min.js` file that I can just drop into the browser without any build steps.

**Comment by eemeli** [comment]
Dunno, tbh. Haven't used Browserify for a while now. My results for googling "babelify transpile node_modules" seem pretty promising, though? The other option is to get your bundler to ignore the package.json's "browser" field, which is what's directing the request to the `.mjs` file.

**Comment by elisehein** [comment]
Thanks @eemeli.

Have you considered publishing a transpiled version of the library so it remains agnostic of a specific build tool/configuration to use? [This is what Rollup seems to suggest](https://github.com/rollup/rollup/wiki/pkg.module).

> Otherwise, whoever uses your library will have to transpile it themselves, including configuring their transpiler to handle your code, which might involve esoteric transforms and conflicting versions of Babel.

I'm only trying to learn and navigate this space myself, so apologies if this suggestion is ill-informed.

**Comment by eemeli** [comment]
The output is already transpiled. Twice, in fact, as it's producing both CommonJS & ES modules. The challenge in your case is that the ES module form is supported by and preferable for most other browser bundlers (e.g. Rollup, Webpack, Parcel) over the CommonJS form, primarily thanks to tree shaking. That's why it's the one that's in the package.json "browser" field.

Do you have a particular reason for using Browserify? You may find other more recent bundlers to be easier to work with.

**Comment by elisehein** [comment]
Yes, I had the same thoughts re browserify yesterday.

Thanks for your help!
