### ISSUE TITLE
v1.3.0 breaks Internet Explorer 11

### ISSUE THREAD

**Issue by jcestibariz** [eemeli/intl-pluralrules#24]
v1.2.2 loads correctly in Internet Explorer 11 but v1.3.0 fails with a syntax error at line 48:

```js
const a = (n, ord) => {
```

**Comment by eemeli** [comment]
Ah, the external dependencies are not getting appropriately ~~polyfilled~~ transpiled (edit: fixed this). Bother, will need to fix.

**Comment by jcestibariz** [comment]
I think the problem is the use of ES6 syntax which is not supported by Internet Explorer, that line used to be:

```js
function a(n, ord) {
```

**Comment by eemeli** [comment]
A fix for this is now released as v1.3.1.
