### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by Fenopiu** [eemeli/intl-pluralrules#7]
Are you planning to build Typescript definitions?

**Comment by eemeli** [comment]
No current plans. The definitions should be the same as for Intl.PluralRules, which I'd expect to be available by default?

**Comment by longlho** [comment]
@Fenopiu 	add `"es2018.intl"` to your `lib` in `tsconfig.json`

**Comment by aeirola** [comment]
Even though TypeScript contains the typings for Intl, it would be useful for the `intl-pluralrules/plural-rules` export to be properly typed.

Currently we need to include 
```typescript
declare module 'intl-pluralrules/plural-rules' {
  const PluralRules: Intl.PluralRules;
  export default PluralRules;
}
```
in our type definitions for us to be able to override our environment implementation in a TypeScript project.

**Comment by eemeli** [comment]
I'd be happy to accept a PR for this.

**Comment by eemeli** [comment]
Closing as fixed.
