### ISSUE TITLE
test262-compliant

### ISSUE THREAD

**Issue by longlho** [eemeli/intl-pluralrules#8]
Are you interested in being test262-compliant?

**Comment by eemeli** [comment]
That does seem like a good idea.

**Comment by longlho** [comment]
It is a TON more work though (it exhaustively checks object prototype descriptors, `toString`...). I can make a PR to get the harness running, but fixing all the possible issues while making it working in IE11 might be tricky. Just FYI

**Comment by eemeli** [comment]
If the harnessing isn't too difficult (and it shouldn't be?) then that would be valuable work, even if we don't fix everything. For [`yaml`](/eemeli/yaml), I did something similar with the full YAML test suite.

**Comment by longlho** [comment]
kk I'll put in a PR soon
